const fs = require('fs');

const content = `export const GRADES = ["3", "4", "5", "6", "7", "8", "9", "10"]
export const SECTIONS = ["A", "B", "C"]

export const CURRICULUM = {
  "3": [
    { week: 1,  title: "Yapay Zeka Nedir?", description: "Yapay zekanin ne oldugunu ogreniyoruz.", activity: "Siniftaki akilli cihazlari listele. Her birinin ne yapabildigini yaz." },
    { week: 2,  title: "Bilgisayarlar Nasil Dusunur?", description: "Bilgisayarlarin talimatlarla calistigini ogreniyoruz.", activity: "Bir robota sandvic yap talimati ver. Adim adim yaz." },
    { week: 3,  title: "Siralama ve Kurallar", description: "Algoritma kavramini oyunla ogreniyoruz.", activity: "Sabah rutinini siraya koy. Kac adim?" },
    { week: 4,  title: "Oruntuler ve Tekrarlar", description: "Bilgisayarlarin oruntuleri nasil buldugunu ogreniyoruz.", activity: "Bir oruntu ciz: kirmizi, mavi, kirmizi, mavi... Devamini tamamla." },
    { week: 5,  title: "Verilerle Tanisiyoruz", description: "Veri nedir? Sayilar ve bilgiler nasil kullanilir?", activity: "Arkadaslarinin dogum aylarini listele. Hangi ayda en cok dogum var?" },
    { week: 6,  title: "Resim Yapan Yapay Zeka", description: "AI nin resim yapabildigini goruyoruz.", activity: "Bir AI ya mutlu bir kedi cizdirin. Sonucu degerlendirin." },
    { week: 7,  title: "Soru Soran Makine", description: "Chatbot nedir? Makineyle nasil konusulur?", activity: "Bir chatbota 3 soru sor. Cevaplari yaz." },
    { week: 8,  title: "Dogru ve Yanlis Bilgi", description: "AI her zaman dogru mu soyler?", activity: "AI nin verdigi bir cevabi kontrol et. Dogru mu yanlis mi?" },
    { week: 9,  title: "Sesli Asistanlar", description: "Siri, Alexa gibi sesli asistanlar nasil calisir?", activity: "Sesli asistana 3 komut ver. Hangisini anladi? Yaz." },
    { week: 10, title: "AI ile Hikaye Yaziyoruz", description: "AI yardimiyla kisa hikaye yazma.", activity: "AI ya ormandaki ejderha hakkinda hikaye baslat. Sen bitir." },
    { week: 11, title: "Makineler Ogrenebilir mi?", description: "Makine ogrenmesine giris.", activity: "10 meyve resmini gor. 3 yeni resme bak: meyve mi degil mi?" },
    { week: 12, title: "Guvenli Internet Kullanimi", description: "Yapay zeka araclarini guvenli kullanma.", activity: "Internette guvenli ve guvensiz durumlari listele." },
    { week: 13, title: "AI ile Muzik", description: "Yapay zeka muzik yapabilir mi?", activity: "Bir AI muzik araci dene. Hangi duyguyu hissettirdi?" },
    { week: 14, title: "Robotlar Neler Yapabilir?", description: "Robot teknolojisi ve kullanim alanlari.", activity: "3 farkli robot bul. Her birinin ne ise yaradigini yaz." },
    { week: 15, title: "AI Oyunlarinda", description: "Video oyunlarinda yapay zeka nasil kullanilir?", activity: "Oynadigin bir oyunu dusun. Bilgisayar dusmani nasil hareket ediyor?" },
    { week: 16, title: "Yariyil Projesi", description: "Bu doneme kadar ogrendiklerini goster.", activity: "Yapay zekay anlatan 5 cumlelik yazi yaz. Bir de resim ciz." },
    { week: 17, title: "Yapay Zeka ve Doga", description: "AI dogay korumak icin nasil kullaniliyor?", activity: "AI nin hayvanlari korudugu bir ornek bul. Anlat." },
    { week: 18, title: "AI ile Ceviri", description: "Dil cevirisi nasil calisir?", activity: "Google Translate ile 5 kelimeyi farkli bir dile cevir." },
    { week: 19, title: "Fotograflari Taniyan AI", description: "Goruntu tanima nedir?", activity: "Telefon kamerasiyla bir nesne tara. AI ne dedi?" },
    { week: 20, title: "AI ile Matematik", description: "Yapay zeka matematik problemlerini cozebilir mi?", activity: "AI ya 3 matematik sorusu sor. Hepsini dogru cozdu mu?" },
    { week: 21, title: "Harita ve Konum AI", description: "Google Maps nasil calisir?", activity: "Evinden okula Google Maps ta yol bak. Kac dakika?" },
    { week: 22, title: "AI Hekimler Yardimcisi mi?", description: "Saglik alaninda yapay zeka.", activity: "Basit bir saglik uygulamasi dene. Sorular sor." },
    { week: 23, title: "Oneri Sistemleri", description: "Netflix, YouTube neden bana bunlari oneriyor?", activity: "YouTube da sana onerilen 5 videoyu listele. Neden onlari onerdi?" },
    { week: 24, title: "AI ve Sanat", description: "Yapay zeka sanatci olabilir mi?", activity: "AI ile bir resim yap. Yanina kendi cizdigin resmi koy." },
    { week: 25, title: "Kisisel Veri Nedir?", description: "Verilerimiz nerede kullaniliyor?", activity: "Kisisel veri olan 5 sey listele. Bunlari kimlerle paylasirsin?" },
    { week: 26, title: "AI ile Haber Okuma", description: "Sahte haberler ve AI.", activity: "Bir haber basligi oku. Gercek mi sahte mi? Nasil anladin?" },
    { week: 27, title: "Gelecegin Meslekleri", description: "AI hangi isleri degistirecek?", activity: "Buyuyunce ne olmak istiyorsun? AI bu meslegi nasil degistirecek?" },
    { week: 28, title: "AI ile Siir Yaziyoruz", description: "Yaratici yazarlikta AI yardimi.", activity: "AI yardimiyla 4 satirlik siir yaz. Konusu: Bahar." },
    { week: 29, title: "Oyun Tasarliyoruz", description: "Basit oyun kurallari ve algoritma.", activity: "Kendi basit kart oyununu tasarla. 3 kural yaz." },
    { week: 30, title: "AI Araclarini Karsilastirma", description: "Farkli AI araclarini deneyin.", activity: "2 farkli AI araci ayni soruyu sor. Cevaplari karsilastir." },
    { week: 31, title: "Empati ve AI", description: "AI duygularimizi anlayabilir mi?", activity: "AI ya uzgun hissediyorum de. Ne cevap verdi?" },
    { week: 32, title: "AI ile Tarih", description: "Yapay zeka tarihimizi arastirmamiza yardimci olabilir.", activity: "AI ya Ataturk hakkinda 3 soru sor." },
    { week: 33, title: "Cevre Dostu AI", description: "AI enerji tuketiyor mu?", activity: "AI nin cevreye etkisi hakkinda 3 bilgi bul." },
    { week: 34, title: "Mini Proje: AI Asistanim", description: "Kendi yapay zeka asistanini tasarla.", activity: "Hayalindeki AI asistani ciz. 5 ozellik listele." },
    { week: 35, title: "Yil Sonu Sunumu Hazirligi", description: "Bu yil ogrendiklerini derle.", activity: "Bu yil yapay zeka hakkinda ogrendigin en onemli 5 seyi yaz." },
    { week: 36, title: "Yil Sonu Projesi", description: "Tum yilin ozeti.", activity: "Yapay zeka ile ilgili bir hayalin var mi? Anlat." },
  ],
  "4": [
    { week: 1,  title: "Yapay Zeka Dunyasi", description: "AI nedir, nerede kullanilir?", activity: "Evinde ve okulunda kullandigin 10 AI urunu listele." },
    { week: 2,  title: "Algoritma Dusuncesi", description: "Adim adim problem cozme.", activity: "Bir yemek tarifini algoritma olarak yaz. Her adimi numarala." },
    { week: 3,  title: "Veriler ve Grafikler", description: "Veri toplama ve gorsellestirme.", activity: "10 arkadasinin favori rengi nedir? Cubuk grafik ciz." },
    { week: 4,  title: "Makine Nasil Ogrenir?", description: "Orneklerden ogrenme konsepti.", activity: "50 kedi-kopek fotografi gordukten sonra 10 yeni fotografa bak." },
    { week: 5,  title: "Dogal Dil Isleme", description: "Bilgisayarlar metni nasil anlar?", activity: "Bir AI ya karmasik bir cumle yaz. Anlayabildi mi?" },
    { week: 6,  title: "Goruntu Tanima", description: "AI fotograflardaki nesneleri nasil tanir?", activity: "Google Lens ile 5 farkli nesneyi tara." },
    { week: 7,  title: "AI ile Hikaye Uretme", description: "Yaratici yazarlikta AI kullanimi.", activity: "AI ile bir macera hikayesi yaz. Sen basla, AI devam etsin." },
    { week: 8,  title: "Oneri Algoritmalari", description: "Spotify, Netflix nasil oneri yapar?", activity: "Dinledigin muzikleri listele. Spotify sana ne oneriyor?" },
    { week: 9,  title: "Chatbot Tasarimi", description: "Basit bir chatbot nasil calisir?", activity: "Okul kutuphanesi icin chatbot tasarla. 10 soru-cevap yaz." },
    { week: 10, title: "Sahte Bilgi Tespiti", description: "Deepfake ve sahte icerik.", activity: "3 haber basligi oku. Gercek mi sahte mi?" },
    { week: 11, title: "AI ve Muzik Uretimi", description: "Yapay zeka muzik besteleyebilir mi?", activity: "Bir AI muzik araciyla kisa melodi olustur." },
    { week: 12, title: "Veri Gizliligi", description: "Kisisel verilerimizi koruma.", activity: "Sosyal medyada paylasimasi tehlikeli olan 10 seyi listele." },
    { week: 13, title: "Robot Programlama Temelleri", description: "Scratch ile basit animasyon.", activity: "Scratch te hareket eden bir karakter programla." },
    { week: 14, title: "AI Saglik Sektorunde", description: "Tibbi goruntu analizi.", activity: "Bir rontgen okuma AI hakkinda arastir. Nasil calisir?" },
    { week: 15, title: "Otonom Araclar", description: "Suruculer araba nasil calisir?", activity: "Tesla Autopilot u arastir. Nasil karar verir?" },
    { week: 16, title: "Yariyil Projesi: AI Gazetesi", description: "AI haberlerini derleyin.", activity: "Bu yariyil yapay zeka hakkinda 3 haber bul. Ozetini yaz." },
    { week: 17, title: "AI ve Spor", description: "Sporda yapay zeka kullanimi.", activity: "Bir spor takiminin AI kullandigi bir ornek bul." },
    { week: 18, title: "Ceviri Teknolojileri", description: "Dil modelleri nasil calisir?", activity: "Bir metni 3 farkli dile cevir. Kaliteyi karsilastir." },
    { week: 19, title: "AI ve Egitim", description: "Yapay zeka ogrenmeyi nasil degistirir?", activity: "AI nin egitimdeki iyi ve kotu yanlarini listele. 5 er madde." },
    { week: 20, title: "Ses Tanima Teknolojisi", description: "Konusmadan metne donusum.", activity: "Sesini kaydet ve metne donustur. Dogruluk oranini degerlendir." },
    { week: 21, title: "AI ile Cografya", description: "Google Earth ve harita teknolojileri.", activity: "Google Earth te okulunu bul. Cevresindeki 5 onemli yeri tanimla." },
    { week: 22, title: "Etik ve Adalet", description: "AI kararlari adil olmali mi?", activity: "Bir AI nin adaletsiz karar verdigi senaryoyu dusun." },
    { week: 23, title: "AI ile Sanat Galerisi", description: "Farkli AI sanat araclarini kesfet.", activity: "3 farkli AI sanat araciyla ayni konuda resim yap." },
    { week: 24, title: "Doga ve Cevre AI", description: "Iklim degisikligi ile mucadelede AI.", activity: "AI nin cevre icin kullanildigi 3 proje bul." },
    { week: 25, title: "AI Kariyer Rehberi", description: "AI alaninda calismak nasil olur?", activity: "AI ile ilgili 5 meslek listele. Her birinin ne yaptigini arastir." },
    { week: 26, title: "Mini Proje: AI Dedektifi", description: "AI ile problem cozme.", activity: "Siniftaki bir problemi AI ile cozmeyi oner." },
    { week: 27, title: "Oyun AI si", description: "Chess engines ve oyun AI lari.", activity: "Satranc AI ina karsi oyna. Kac hamlede kaybettin?" },
    { week: 28, title: "AI ve Habercilik", description: "Gazetecilikte AI kullanimi.", activity: "Bir haberi AI ya ozetle. Dogru ozetti mi?" },
    { week: 29, title: "Gelecekte AI", description: "10 yil sonra AI nasil olacak?", activity: "2035 yilinda yapay zekanin hayatimizi nasil degistirecegini hayal et." },
    { week: 30, title: "AI ile Siir ve Edebiyat", description: "Edebi yaraticilikata AI.", activity: "Favori kitabinin konusunu AI ya ver. Farkli bir son yazdir." },
    { week: 31, title: "Veri Analizi Temelleri", description: "Basit veri okuma ve yorumlama.", activity: "Bir cubuk grafik bul. Verileri oku ve 3 sonuc cikar." },
    { week: 32, title: "AI Guvenligi", description: "Siber guvenlikte yapay zeka.", activity: "Guclu sifre nasil olmali? AI yardimiyla 5 kural yaz." },
    { week: 33, title: "Yaratici AI Projem", description: "Kendi AI projen.", activity: "Hayalindeki AI uygulamasini tasarla." },
    { week: 34, title: "Akran Degerlendirmesi", description: "Arkadaslarinin projelerini degerlendir.", activity: "3 arkadasinin projesine 1 olumlu, 1 gelisim onerisi yaz." },
    { week: 35, title: "Yil Sonu Hazirligi", description: "Yilin en iyi calismalarini sec.", activity: "Bu yilki en iyi 3 calismana bak. Neden bunlari sectin?" },
    { week: 36, title: "Yil Sonu Sunumu", description: "Ogrendiklerini paylas.", activity: "Bu yil yapay zeka hakkinda ogrendigin en onemli seyi anlat." },
  ],
  "5": [
    { week: 1,  title: "Yapay Zeka Tarihcesi", description: "AI nasil ortaya cikti? Alan Turing den GPT ye.", activity: "AI tarihindeki 5 onemli olayi kronolojik siraya koy." },
    { week: 2,  title: "Makine Ogrenmesi Temelleri", description: "Denetimli ve denetimsiz ogrenme.", activity: "E-posta spam filtresi nasil calisir? 5 cumleyle acikla." },
    { week: 3,  title: "Veri Neden Onemli?", description: "Big Data ve veri kalitesi.", activity: "Iyi veri ve kotu veri ornekleri ver. Her kategoriden 3 er ornek." },
    { week: 4,  title: "Sinir Aglari", description: "Insan beyinden ilham: yapay sinir aglari.", activity: "Sinir aginin nasil calistigini diyagramla anlat." },
    { week: 5,  title: "Dogal Dil Isleme", description: "Chatbot lar nasil bizi anlar?", activity: "Bir chatbotla 10 mesajlik konusma yap. Guclu ve zayif yonlerini listele." },
    { week: 6,  title: "Bilgisayar Gormesi", description: "Goruntu siniflandirma ve nesne tespiti.", activity: "YOLO veya benzer nesne tespit sistemini arastir." },
    { week: 7,  title: "Oneri Sistemleri", description: "Collaborative filtering nasil calisir?", activity: "Amazon un oneri sistemi nasil calisir? Adimlarini yaz." },
    { week: 8,  title: "AI ile Veri Analizi", description: "Temel istatistik ve veri gorsellestirme.", activity: "Siniftaki ogrencilerin not ortalamasini hesapla. Pasta grafik ciz." },
    { week: 9,  title: "Prompt Muhendisligi", description: "AI ya dogru soru sormak.", activity: "Ayni konuda 3 farkli prompt yaz. Sonuclari karsilastir." },
    { week: 10, title: "Generatif AI", description: "ChatGPT, DALL-E nasil calisir?", activity: "Bir generatif AI ya karmasik gorev ver. Sonucu degerlendir." },
    { week: 11, title: "AI Etigi", description: "Yapay zekanin toplumsal etkileri.", activity: "AI kullaniminda 3 etik sorun tanimla. Her biri icin cozum oner." },
    { week: 12, title: "Deepfake ve Dezinformasyon", description: "Sahte icerikleri tespit etme.", activity: "Deepfake videoyu gercekten ayirt etmek icin 5 ipucu yaz." },
    { week: 13, title: "Scratch ile AI Projesi", description: "Gorsel programlama ile AI projesi.", activity: "Scratch te basit soru-cevap programi yap." },
    { week: 14, title: "Saglikta AI Uygulamalari", description: "Kanser tespiti, ilac gelistirme.", activity: "AlphaFold projesini arastir. Bilime nasil katki sagladi?" },
    { week: 15, title: "Ulasimda AI", description: "Otonom araclar, trafik yonetimi.", activity: "Waymo nun otonom arac sistemini arastir. 5 cumleyle anlat." },
    { week: 16, title: "Yariyil Projesi", description: "Bir AI problemini arastir ve coz.", activity: "Gunluk hayatta bir problemi sec. AI nasil cozebilir?" },
    { week: 17, title: "AI ve Sanat", description: "Midjourney, Stable Diffusion.", activity: "Ayni prompt la 3 farkli AI sanat aracina resim yaptir." },
    { week: 18, title: "Ses ve Muzik AI", description: "Suno, Udio gibi araclar.", activity: "AI ile kisa muzik parcasi olustur." },
    { week: 19, title: "Cevre ve Surdurulebilirlik", description: "AI iklim degisikligi ile mucadelede.", activity: "AI nin karbon ayak izini azaltmada kullanildigi 3 proje bul." },
    { week: 20, title: "Finans ve AI", description: "Borsa tahmini, dolandiricilik tespiti.", activity: "Kredi karti dolandiriciliginda AI nasil calisir?" },
    { week: 21, title: "Egitimde Kisiselestirme", description: "Adaptive learning sistemleri.", activity: "Khan Academy nin AI destekli sistemini incele." },
    { week: 22, title: "Robot ve Otomasyon", description: "Fabrikalar ve robotlar.", activity: "Tesla fabrikasindaki robot sistemini arastir." },
    { week: 23, title: "Oyun AI si", description: "AlphaGo ve oyun teorisi.", activity: "AlphaGo nun Go macini kazanmasini arastir. Neden onemliyd?" },
    { week: 24, title: "Sosyal Medya Algoritmalari", description: "Feed siralamasi ve balonlar.", activity: "Instagram feed algoritmasi nasil calisir?" },
    { week: 25, title: "AI ile Arastirma", description: "Akademik arastirmada AI araclari.", activity: "Bir konuyu AI yardimiyla arastir. Kaynaklari dogrula." },
    { week: 26, title: "Yapay Zeka Yasalari", description: "AI duzenlemeleri ve yasalar.", activity: "AB nin AI Yasasi hakkinda arastir. 3 onemli kurali listele." },
    { week: 27, title: "Mini Proje: AI Haberci", description: "Yapay zeka haberlerini takip et.", activity: "Bu haftaki en onemli AI haberini bul. Ozetini yaz." },
    { week: 28, title: "Gelecegin Teknolojileri", description: "AGI, kuantum AI.", activity: "AGI nedir? Insanliga nasil etkileri olabilir?" },
    { week: 29, title: "AI ile Dil Ogrenimi", description: "Duolingo ve dil AI lari.", activity: "Duolingo nun AI sistemini arastir." },
    { week: 30, title: "Veri Bilimi Temelleri", description: "Python ile basit veri analizi kavramlari.", activity: "Bir veri setine bak. 3 gozlem yaz. Grafik yorumla." },
    { week: 31, title: "AI ile Kodlama", description: "GitHub Copilot ve kod yardicilari.", activity: "Copilot veya benzer aracla basit kod yaz." },
    { week: 32, title: "Biyometri ve Guvenlik", description: "Yuz tanima, parmak izi.", activity: "Yuz tanima teknolojisinin avantaj ve dezavantajlarini listele." },
    { week: 33, title: "Son Proje Planlamasi", description: "Yil sonu projesini planla.", activity: "Yil sonu projen icin konu sec. Problem, cozum, araclar planini yaz." },
    { week: 34, title: "Proje Gelistirme", description: "Son projeyi gelistir.", activity: "Projenin ilk taslagini tamamla." },
    { week: 35, title: "Proje Sunumu Hazirligi", description: "Sunum teknikleri.", activity: "Projen icin 5 dakikalik sunum hazirla." },
    { week: 36, title: "Yil Sonu Sunumu", description: "Projeni sinifa sun.", activity: "Yil boyunca ogrendigin en onemli 3 kavrami paylas." },
  ],
  "6": [
    { week: 1,  title: "AI Ekosistemi", description: "AI turleri: dar AI, genel AI, super AI.", activity: "Dar AI ve Genel AI arasindaki farki ornek vererek acikla." },
    { week: 2,  title: "Python a Giris", description: "Programlamanin temelleri.", activity: "Python da Merhaba Dunya yaz. Degisken ve print komutlarini ogren." },
    { week: 3,  title: "Veri Turleri ve Yapilari", description: "Liste, sozluk, sayi, metin.", activity: "Python da 5 kisilik sinif listesi olustur. Notlarini sozluk olarak sakla." },
    { week: 4,  title: "Kosullar ve Donguler", description: "if-else ve for donguleri.", activity: "Notlari degerlendiren Python programi yaz." },
    { week: 5,  title: "Fonksiyonlar", description: "Fonksiyon tanimlama ve kullanma.", activity: "Cevre ve alan hesaplayan fonksiyonlar yaz." },
    { week: 6,  title: "Veri Analizi: Pandas Girisi", description: "Pandas ile veri okuma.", activity: "Basit bir CSV dosyasi olustur. Pandas ile oku." },
    { week: 7,  title: "Veri Gorsellestirme", description: "Matplotlib ile grafik cizme.", activity: "Sinif notlarini bar chart ile gorsellesir." },
    { week: 8,  title: "Makine Ogrenmesi Nedir?", description: "Denetimli ogrenme kavramlari.", activity: "Scikit-learn ile basit lineer regresyon modeli kur." },
    { week: 9,  title: "Siniflandirma Algoritmalari", description: "KNN, Decision Tree.", activity: "Iris veri seti ile siniflandirma modeli kur." },
    { week: 10, title: "Model Degerlendirme", description: "Accuracy, precision, recall.", activity: "Modelinin dogrulugunu hesapla. Confusion matrix olustur." },
    { week: 11, title: "Dogal Dil Isleme Temelleri", description: "Tokenization, stemming.", activity: "Bir metni tokenize et. En cok kullanilan 10 kelimeyi bul." },
    { week: 12, title: "Sentiment Analizi", description: "Duygu analizi nedir?", activity: "10 farkli tweet icin duygu analizi yap." },
    { week: 13, title: "Goruntu Isleme Temelleri", description: "OpenCV ile temel islemler.", activity: "Bir resmi gri tonlamaya cevir. Kenarlari tespit et." },
    { week: 14, title: "Yapay Sinir Aglari", description: "Perceptron ve cok katmanli aglar.", activity: "Basit sinir agi mimarisini ciz." },
    { week: 15, title: "Derin Ogrenme Girisi", description: "CNN, RNN nedir?", activity: "CNN nin goruntu tanimada nasil calistigini adim adim acikla." },
    { week: 16, title: "Yariyil Projesi", description: "Bir ML modeli kur ve degerlendir.", activity: "Sectigin veri seti uzerinde siniflandirma modeli kur." },
    { week: 17, title: "Transfer Learning", description: "Hazir modelleri kullanma.", activity: "Hugging Face ten bir model indir. Basit gorevde test et." },
    { week: 18, title: "API Kullanimi", description: "API nedir? Nasil kullanilir?", activity: "Gemini API ile basit chatbot yaz." },
    { week: 19, title: "Veri Temizleme", description: "Eksik veri, aykiri deger.", activity: "Hatali veri setini temizle. Adimlarini raporla." },
    { week: 20, title: "Feature Engineering", description: "Ozellik muhendisligi nedir?", activity: "Veri setine yeni ozellikler ekle. Modelin performansi degisti mi?" },
    { week: 21, title: "Hiperparametre Ayari", description: "Grid search ve optimizasyon.", activity: "Modelini grid search ile optimize et." },
    { week: 22, title: "AI Projesinin Yasam Dongusu", description: "Problem, veri, model, deploy.", activity: "Gercek AI projesi icin 6 asamali plan yaz." },
    { week: 23, title: "Etik ve Onyargi", description: "Algoritmik onyargi nedir?", activity: "Bir AI sisteminde onyargi ornegi bul. Nasil giderilebilir?" },
    { week: 24, title: "Aciklanabilir AI", description: "XAI nedir? Model seffafligi.", activity: "Black-box modelin kararini nasil aciklarsın? LIME veya SHAP arastir." },
    { week: 25, title: "Edge AI", description: "Telefon ve IoT cihazlarinda AI.", activity: "TensorFlow Lite i arastir. Hangi cihazlarda calisir?" },
    { week: 26, title: "Kaggle Yarismasi", description: "Veri bilimi yarismalar.", activity: "Kaggle da baslangic yarismasi incele. Nasil katilirsin?" },
    { week: 27, title: "AI Startup Dunyasi", description: "Basarili AI sirketleri.", activity: "3 basarili AI startup ini arastir. Ne sorunu cozuyorlar?" },
    { week: 28, title: "Son Proje Planlama", description: "Yil sonu projesi icin konu belirle.", activity: "3 potansiyel proje konusu listele." },
    { week: 29, title: "Proje Veri Toplama", description: "Veri toplama ve hazirlama.", activity: "Projen icin veri topla. Veri kalitesini degerlendir." },
    { week: 30, title: "Proje Model Gelistirme", description: "Modeli kur ve egit.", activity: "Projen icin ilk modelini kur. Dogruluk oranini olc." },
    { week: 31, title: "Proje Iyilestirme", description: "Modeli optimize et.", activity: "Modelini gelistir. Onceki dogrulukla karsilastir." },
    { week: 32, title: "Proje Dokumantasyon", description: "Raporlama ve aciklama.", activity: "Projen icin teknik rapor yaz." },
    { week: 33, title: "Akran Degerlendirmesi", description: "Arkadaslarinin projelerini incele.", activity: "2 arkadasinin projesine teknik geri bildirim ver." },
    { week: 34, title: "Sunum Hazirligi", description: "Teknik sunum nasil yapilir?", activity: "7 dakikalik sunum hazirla. Demo dahil olsun." },
    { week: 35, title: "Final Sunumu", description: "Projeyi sinifa sun.", activity: "Projeni sun. Sorulari cevapla." },
    { week: 36, title: "Yil Sonu Degerlendirmesi", description: "Yili degerlendir, planla.", activity: "Bu yil ne ogrendin? Gelecek yil ne yapmak istiyorsun?" },
  ],
  "7": [
    { week: 1,  title: "Ileri Makine Ogrenmesi", description: "Ensemble yontemler, Random Forest.", activity: "Random Forest ile siniflandirma modeli kur. Decision Tree ile karsilastir." },
    { week: 2,  title: "Derin Ogrenme: CNN", description: "Evrisimli sinir aglari.", activity: "MNIST veri seti ile el yazisi tanima modeli kur." },
    { week: 3,  title: "RNN ve LSTM", description: "Sirali veri ve zaman serileri.", activity: "Hava durumu verisi ile gelecek tahmini modeli kur." },
    { week: 4,  title: "Transformer Mimarisi", description: "Attention mekanizmasi nedir?", activity: "BERT veya GPT mimarisini arastir. Attention mekanizmasini goster." },
    { week: 5,  title: "Buyuk Dil Modelleri", description: "GPT, Gemini, Claude nasil calisir?", activity: "3 farkli LLM ye ayni soruyu sor. Cevaplari karsilastir." },
    { week: 6,  title: "Prompt Engineering Ileri", description: "Chain-of-thought, few-shot prompting.", activity: "Chain-of-thought ile karmasik problemi AI ya cozdu." },
    { week: 7,  title: "RAG Sistemleri", description: "Retrieval Augmented Generation.", activity: "RAG in nasil calistigini anlat. Hangi problemleri cozer?" },
    { week: 8,  title: "Fine-tuning", description: "Onceden egitilmis modelleri ozellestirme.", activity: "Hugging Face ile bir modeli fine-tune et." },
    { week: 9,  title: "Uretken AI Sanat", description: "Stable Diffusion, DALL-E 3.", activity: "Ayni prompt icin farkli parametrelerle 5 goruntu uret." },
    { week: 10, title: "Video ve Ses AI", description: "Sora, Suno, ElevenLabs.", activity: "Bir AI ses klonlama aracini dene. Etik boyutunu tartis." },
    { week: 11, title: "AI Guvenligi", description: "Adversarial attacks, model poisoning.", activity: "Adversarial attack nedir? Bir ornek arastir." },
    { week: 12, title: "Federated Learning", description: "Merkezi olmayan AI egitimi.", activity: "Federated Learning in gizlilik avantajlarini acikla." },
    { week: 13, title: "Kuantum AI", description: "Kuantum bilgisayar ve AI.", activity: "Kuantum ustunlugu nedir? AI ya nasil etki eder?" },
    { week: 14, title: "Coklu Modalite", description: "GPT-4V, Gemini Vision.", activity: "Bir cok modaliiteli modele goruntu gonder. Analizi degerlendir." },
    { week: 15, title: "AI Ajanlari", description: "AutoGPT, LangChain.", activity: "Bir AI ajaninin gorevi nasil tamamladigini arastir." },
    { week: 16, title: "Yariyil Projesi", description: "Ileri duzey ML projesi.", activity: "Gercek dunya verisiyle tam ML pipeline kur." },
    { week: 17, title: "MLOps Temelleri", description: "Model dagitimi ve takibi.", activity: "MLflow veya benzer aracla model takibi yap." },
    { week: 18, title: "AI Urun Tasarimi", description: "AI tabanli urun nasil tasarlanir?", activity: "Bir AI urunu tasarla: kullanici hikayeleri, ozellikler." },
    { week: 19, title: "A/B Testi", description: "AI sistemlerinde deney tasarimi.", activity: "Iki farkli model icin A/B testi tasarla." },
    { week: 20, title: "AI Duzenlemeleri", description: "Global AI politikalari.", activity: "AB, ABD ve Cin in AI politikalarini karsilastir." },
    { week: 21, title: "Robotik ve AI", description: "ROS, robot programlama.", activity: "Boston Dynamics robotlarini arastir. Hangi AI sistemleri kullaniyor?" },
    { week: 22, title: "Biyoinformatik AI", description: "Genomik veri analizi.", activity: "AlphaFold un protein katlama problemini nasil cozdugun arastir." },
    { week: 23, title: "Fintech AI", description: "Algoritmik trading, risk analizi.", activity: "Algoritmik trading nedir? Avantaj ve riskleri nelerdir?" },
    { week: 24, title: "Savunma ve AI Etigi", description: "Otonom silahlar ve etik.", activity: "Otonom silahlarin yasaklanmasi tartismasini arastir." },
    { week: 25, title: "Acik Kaynak AI", description: "Llama, Mistral, acik modeller.", activity: "Acik kaynak ve kapali kaynak AI modellerini karsilastir." },
    { week: 26, title: "AI Startup Kurma", description: "Bir AI sirketi nasil kurulur?", activity: "Kendi AI startup fikrini gelistir. Pitch deck ana basliklarini yaz." },
    { week: 27, title: "Arastirma Makalesi Okuma", description: "Akademik AI literaturü.", activity: "Arxiv den bir AI makalesi sec. Ozetini yaz." },
    { week: 28, title: "Son Proje Baslangici", description: "Kapsamli AI projesi.", activity: "Proje teklifi yaz: problem, yaklasim, veri, beklenen sonuc." },
    { week: 29, title: "Proje Uygulama I", description: "Veri toplama ve hazirlama.", activity: "Proje verinizi topla ve EDA yap." },
    { week: 30, title: "Proje Uygulama II", description: "Model kurma ve egitim.", activity: "Projen icin en az 2 farkli model dene." },
    { week: 31, title: "Proje Uygulama III", description: "Optimizasyon ve fine-tuning.", activity: "En iyi modelini sec ve optimize et." },
    { week: 32, title: "Proje Deploy", description: "Modeli web e tasima.", activity: "Streamlit veya Gradio ile modelini web uygulamasina donustur." },
    { week: 33, title: "Proje Dokumantasyon", description: "Teknik rapor ve README.", activity: "Projen icin kapsamli teknik dokumantasyon yaz." },
    { week: 34, title: "Akran Degerlendirmesi", description: "Capraz degerlendirme.", activity: "2 arkadasinin projesine detayli teknik geri bildirim ver." },
    { week: 35, title: "Final Sunumu Hazirligi", description: "Demo ve sunum.", activity: "10 dakikalik sunum hazirla. Demo dahil." },
    { week: 36, title: "Yil Sonu Sunumu", description: "Projeni sun ve yili degerlendir.", activity: "Projeni sun. Gelecek yil icin AI ogrenme yol haritani paylas." },
  ],
  "8": [
    { week: 1,  title: "AI Arastirma Metodolojisi", description: "Bilimsel yontem ve AI.", activity: "Bir AI arastirma sorusu formule et. Hipotez yaz." },
    { week: 2,  title: "Istatistik ve Olasilik", description: "AI icin temel istatistik.", activity: "Bayes teoremi nedir? Spam filtresinde nasil kullanilir?" },
    { week: 3,  title: "Optimizasyon Teorisi", description: "Gradient descent derinlemesi.", activity: "Farkli learning rate lerin model performansina etkisini test et." },
    { week: 4,  title: "GAN lar", description: "Generative Adversarial Networks.", activity: "GAN in egitim surecini anlat. Generator vs Discriminator." },
    { week: 5,  title: "Diffusion Modeller", description: "Stable Diffusion nasil calisir?", activity: "Diffusion modelinin noise removal surecini diyagramla goster." },
    { week: 6,  title: "Reinforcement Learning", description: "Odul ve ceza sistemi.", activity: "Q-learning algoritmasini anlat. Basit gridworld problemini coz." },
    { week: 7,  title: "Multi-Agent Systems", description: "Coklu ajan etkilesimi.", activity: "Cok ajanli sistem tasarla. Ajan rolleri ve etkilesimleri tanimla." },
    { week: 8,  title: "Neuro-symbolic AI", description: "Sembolik ve baglantisal AI.", activity: "Sembolik AI ve derin ogrenmenin guclu ve zayif yonlerini karsilastir." },
    { week: 9,  title: "AI Yorumlanabilirligi", description: "LIME, SHAP, saliency maps.", activity: "Bir modelin kararini SHAP degerleriyle acikla." },
    { week: 10, title: "Buyuk Olcek AI Altyapisi", description: "GPU, TPU, dagitik egitim.", activity: "GPT-4 egitiminin maliyetini arastir." },
    { week: 11, title: "AI ve Biyometri", description: "Yuz, ses, davranis tanima.", activity: "Yuz tanImanin hukuki boyutlarini arastir." },
    { week: 12, title: "Otonom Sistemler", description: "Drone, robot kararlari.", activity: "Askeri drone lardaki AI sistemlerini arastir. Etik sorunlari tartis." },
    { week: 13, title: "LLM Fine-tuning", description: "LoRA, PEFT yontemleri.", activity: "LoRA ile kucuk bir modeli fine-tune et." },
    { week: 14, title: "AI Guvenlik Aciklari", description: "Prompt injection, jailbreak.", activity: "3 farkli prompt injection turunu arastir." },
    { week: 15, title: "AI ve Hukuk", description: "Telif hakki, sorumluluk.", activity: "AI tarafindan uretilen icerik icin telif hakki araştir." },
    { week: 16, title: "Yariyil Projesi", description: "Ozgun AI sistemi gelistir.", activity: "Gercek problemi cozen deploy edilmis AI uygulamasi gelistir." },
    { week: 17, title: "AI Urun Yonetimi", description: "AI PM nin rolu.", activity: "Bir AI urunu icin PRD yaz." },
    { week: 18, title: "Veri Muhendisligi", description: "ETL pipeline lar.", activity: "Basit ETL pipeline tasarla ve uygula." },
    { week: 19, title: "Model Monitoring", description: "Concept drift, model decay.", activity: "Model performansini izleyen sistem tasarla." },
    { week: 20, title: "AI ve Saglik", description: "Radyoloji AI, ilac kesfi.", activity: "FDA onaylu bir AI tibbi cihazini arastir." },
    { week: 21, title: "Dogal Dil Uretimi", description: "Metin ozetleme, soru olusturma.", activity: "Metni ozzetleyen ve soru olusturan sistem kur." },
    { week: 22, title: "Cok Dilli AI", description: "Capraz dil transferi.", activity: "Turkce icin fine-tune edilmis model bul. Test et." },
    { week: 23, title: "AI ve Egitim Sistemi", description: "Adaptif ogrenme platformlari.", activity: "Turkiye de kullanilan AI egitim araclarini arastir." },
    { week: 24, title: "AI Ekonomisi", description: "Otomasyon ve isgücü.", activity: "Hangi meslekler AI dan en cok etkilenecek? 10 yillik tahmin yap." },
    { week: 25, title: "AI ve Demokrasi", description: "Secim mudahalesi, propaganda.", activity: "AI nin secim sureclerine etkisini arastir." },
    { week: 26, title: "Acik Kaynak Toplulugu", description: "Hugging Face, GitHub.", activity: "Hugging Face e bir model veya dataset yukle." },
    { week: 27, title: "AI Kariyer Planlamasi", description: "Data scientist, ML engineer.", activity: "3 AI kariyeri sec. Gereken beceriler ve egitim yolunu arastir." },
    { week: 28, title: "Kapsamli Proje Baslangici", description: "Diploma projesi niteliğinde.", activity: "Ozgun AI problemi sec. Detayli proje teklifi yaz." },
    { week: 29, title: "Proje: Literatur Taramasi", description: "Ilgili calismalari incele.", activity: "Projen konusunda 5 akademik makale bul. Ozetlerini karsilastir." },
    { week: 30, title: "Proje: Sistem Tasarimi", description: "Mimari ve teknik kararlar.", activity: "Projenin sistem mimarisini ciz ve belgele." },
    { week: 31, title: "Proje: Uygulama", description: "Gelistirme ve test.", activity: "Projenin ana bilesenlerini tamamla." },
    { week: 32, title: "Proje: Degerlendirme", description: "Kapsamli test ve analiz.", activity: "Projenin performansini coklu metriklerle degerlendir." },
    { week: 33, title: "Proje: Iyilestirme", description: "Geri bildirim ve optimizasyon.", activity: "Akran geri bildirimini al. Projeyi iyilestir." },
    { week: 34, title: "Proje: Yayinlama", description: "GitHub ve dokumantasyon.", activity: "Projeyi GitHub a yukle. Kapsamli README yaz." },
    { week: 35, title: "Final Sunumu Hazirligi", description: "Konferans tarzi sunum.", activity: "15 dakikalik akademik sunum hazirla." },
    { week: 36, title: "Yil Sonu Konferansi", description: "Projeni paylas.", activity: "Projeyi sun. Bir sonraki adim icin hedef belirle." },
  ],
  "9": [
    { week: 1,  title: "AI Arastirma Dunyasi", description: "Arxiv, NeurIPS, ICML.", activity: "Bu yilin en onemli AI makalesini bul. Abstract i Turkce ye cevir." },
    { week: 2,  title: "Ileri Matematik: Lineer Cebir", description: "Matris, vektor, oz deger.", activity: "PCA yi lineer cebir terimleriyle acikla." },
    { week: 3,  title: "Olasilik Teorisi Ileri", description: "Bayesian inference, MLE.", activity: "Bayesian ve Frequentist yaklasimlarini karsilastir." },
    { week: 4,  title: "Bilgi Graflari", description: "Knowledge graphs ve semantic web.", activity: "Bir bilgi grafi olustur: kendi alanin veya ilgi konun hakkinda." },
    { week: 5,  title: "Causal Inference", description: "Nedensellik vs korelasyon.", activity: "3 korelasyon ornegi bul. Bunlar nedensellik mi? Acikla." },
    { week: 6,  title: "Ileri NLP", description: "Named entity recognition, coreference.", activity: "spaCy ile bir metin uzerinde NER uygula." },
    { week: 7,  title: "Konusma AI Sistemleri", description: "Dialogue systems, task-oriented bots.", activity: "Kendi alanin icin gorev odakli chatbot mimarisi tasarla." },
    { week: 8,  title: "Cok Modalite Ileri", description: "CLIP, Flamingo, GPT-4V.", activity: "Cok modaliiteli modelle karmasik goruntu analizi yap." },
    { week: 9,  title: "AI ve Yaraticilik", description: "Yaraticilik olcumu ve AI.", activity: "AI yaratici olabilir mi? Bir kompozisyon yaz ve savun." },
    { week: 10, title: "Norobilim ve AI", description: "Beyinden ilham alan algoritmalar.", activity: "Hippocampus un bellekteki rolunu arastir. AI ya nasil ilham verdi?" },
    { week: 11, title: "AI Felsefesi", description: "Bilim, ozgur irade, Cin odasi.", activity: "Searle in Cin odasi argumani ni degerlendir." },
    { week: 12, title: "Varoluusal Risk", description: "AI guvenligi ve hizalama.", activity: "AI alignment problemi nedir? Cozum yaklasimlarini arastir." },
    { week: 13, title: "Constitutional AI", description: "Anthropic in yaklasimi.", activity: "Constitutional AI yi arastir. RLHF ile farklari nelerdir?" },
    { week: 14, title: "AI ve Siyaset Bilimi", description: "Teknoloji politikasi.", activity: "Bir ulkenin AI stratejisi belgesini oku. Ana hedefleri ozetle." },
    { week: 15, title: "Kuresel AI Yarisi", description: "ABD, Cin, AB rekabeti.", activity: "AI ciplerindeki kuresel rekabeti arastir. Turkiye nin konumu nedir?" },
    { week: 16, title: "Yariyil Projesi", description: "Ozgun arastirma projesi.", activity: "Yeni bir AI yontemi veya uygulamasi oner." },
    { week: 17, title: "AI Startup Ekosistemi", description: "Venture capital ve AI.", activity: "Bu yil en cok yatirim alan 5 AI startup ini arastir." },
    { week: 18, title: "AI Muhendisligi", description: "Sistem tasarimi ve olcekleme.", activity: "1 milyar kullanicili AI sisteminin mimarisini tasarla." },
    { week: 19, title: "AI ve Surdurulebilirlik", description: "Enerji tuketimi ve yesil AI.", activity: "GPT-4 un karbon ayak izini hesapla." },
    { week: 20, title: "AI ve Insan Haklari", description: "Gozetim, mahremiyet, ozgurluk.", activity: "Cin deki sosyal kredi sistemini arastir. Insan haklari boyutunu tartis." },
    { week: 21, title: "Saglikta AI Ileri", description: "Klinik karar destek sistemleri.", activity: "Bir radyoloji AI sisteminin klinik deneme sonuclarini degerlendir." },
    { week: 22, title: "AI ve Hukuk Ileri", description: "AI hukuku, sorumluluk rejimi.", activity: "Tesla kazasinda sorumluluk kime ait? Hukuki analiz yap." },
    { week: 23, title: "AI ve Gazetecilik", description: "Otomatik haber yazimi.", activity: "Reuters un otomatik haber sistemini arastir." },
    { week: 24, title: "Hesaplamali Sosyal Bilim", description: "Buyuk veri ile toplumu anlama.", activity: "Twitter verisi ile bir sosyal analiz yap." },
    { week: 25, title: "AI Tabanli Siber Guvenlik", description: "AI ile siber saldiri ve savunma.", activity: "AI kullanan bir siber saldiri teknigini arastir." },
    { week: 26, title: "Gelecegin Arayuzleri", description: "BCI, XR ve AI.", activity: "Neuralink i arastir. AI ile butunlesik BCI nin gelecegi nedir?" },
    { week: 27, title: "Post-AGI Senaryo", description: "AGI sonrasi dunya.", activity: "AGI gerceklesirse ilk 10 yilda neler degisir? Senaryo yaz." },
    { week: 28, title: "Kapsamli Arastirma Projesi", description: "Akademik kalitede proje.", activity: "Ozgun arastirma sorusu belirle. Metodoloji plani yaz." },
    { week: 29, title: "Literatur Taramasi", description: "Research gap bul.", activity: "Alaninda cozulmemis 3 acik problem tespit et." },
    { week: 30, title: "Metodoloji ve Uygulama", description: "Araştirmayı uygula.", activity: "Deneyini tasarla ve ilk sonuclari elde et." },
    { week: 31, title: "Analiz ve Yorumlama", description: "Sonuclari yorumla.", activity: "Sonucllarini istatistiksel olarak analiz et." },
    { week: 32, title: "Makale Yazimi", description: "Akademik makale formati.", activity: "Arastirmandan conference paper taslagi yaz." },
    { week: 33, title: "Peer Review Sureci", description: "Akademik degerlendirme.", activity: "Bir arkadasinin makalesini peer review yap." },
    { week: 34, title: "Revizyon ve Finalizasyon", description: "Geri bildirimleri uygula.", activity: "Makaleni revize et. Final versiyonu hazirla." },
    { week: 35, title: "Konferans Sunumu", description: "Akademik sunum.", activity: "20 dakikalik akademik sunum yap." },
    { week: 36, title: "Yil Sonu ve Kariyer Plani", description: "Universite ve AI kariyeri.", activity: "AI alaninda hangi universite programlarini hedefliyorsun? Planla." },
  ],
  "10": [
    { week: 1,  title: "AI Teorisi Derinlemesi", description: "PAC learning, VC dimension.", activity: "VC dimension in model karmasikligiyla iliskisini matematiksel acikla." },
    { week: 2,  title: "Bilgi Teorisi", description: "Entropy, mutual information.", activity: "Karar agacinda information gain nasil kullanilir? Turet." },
    { week: 3,  title: "Oyun Teorisi ve AI", description: "Nash dengesi, stratejik dusunce.", activity: "Iki oyunculu oyunda Nash dengesini bul. AI nasil kullanir?" },
    { week: 4,  title: "Ileri Optimizasyon", description: "Adam, AdaGrad, momentum.", activity: "Farkli optimizatorlerin ayni probleme etkisini karsilastir." },
    { week: 5,  title: "Bayesian Derin Ogrenme", description: "Belirsizlik tahminleme.", activity: "Bayesian neural network ile regresyon problemi coz." },
    { week: 6,  title: "Meta-Learning", description: "Few-shot ve zero-shot ogrenme.", activity: "MAML algoritmasini arastir. 5 cumleyle acikla." },
    { week: 7,  title: "Noral Mimari Arama", description: "AutoML ve NAS.", activity: "AutoML ile model mimarisi arama yap." },
    { week: 8,  title: "Ileri RL", description: "PPO, SAC, model tabanli RL.", activity: "OpenAI Gym ile RL ajani egit. Ogrenme egrisini ciz." },
    { week: 9,  title: "AI Guvenligi Ileri", description: "Formal verification, robustness.", activity: "Bir modelin belirli giris uzayinda guvenligini nasil dogrulamak?" },
    { week: 10, title: "Buyuk Olcek Sistem Tasarimi", description: "Distributed ML, federated.", activity: "100 milyon kullanicili ML sisteminin tam mimarisini tasarla." },
    { week: 11, title: "AI Arastirma Metodolojisi Ileri", description: "Ablation studies, baselines.", activity: "Bir makale sec. Ablation study sini yeniden uret." },
    { week: 12, title: "Yeni Paradigmalar", description: "State space models, Mamba.", activity: "Mamba mimarisini arastir. Transformer dan farklari neler?" },
    { week: 13, title: "Foundation Models", description: "GPT-4, Gemini Ultra mimarileri.", activity: "Foundation model nedir? Uzmanlik modelinden farki nedir?" },
    { week: 14, title: "AI Ekonomi Politikasi", description: "Ulusal AI stratejileri.", activity: "Turkiye nin bir ulusal AI stratejisi taslagi yaz." },
    { week: 15, title: "AI ve Insan Gelisimi", description: "Uzun vadeli etki analizi.", activity: "AI nin insanlik tarihindeki 3 en buyuk etkisini tahmin et." },
    { week: 16, title: "Yariyil Projesi", description: "Ozgun arastirma katkisi.", activity: "Bir AI problemine ozgun cozum oner. Teorik ve deneysel kanit sun." },
    { week: 17, title: "AI ve Disiplinlerarasi Calisma", description: "AI+X arastirma alanlari.", activity: "Ilgi alanin ile AI yi birlestir. Ozgun arastirma sorusu uret." },
    { week: 18, title: "Startup tan Urune", description: "0 dan 1 e AI urunu.", activity: "Bir AI urunun tam yol haritasini ciz." },
    { week: 19, title: "AI ve Sosyal Etki", description: "AI for good projeleri.", activity: "Turkiye deki bir sosyal problemi AI ile coz. Proje plani yaz." },
    { week: 20, title: "Ileri Etik Tartismalar", description: "Trolley problem, alignment.", activity: "AI trolley problem varyantlarini arastir. Kendi etik cerceveni olustur." },
    { week: 21, title: "Post-Human Soylemi", description: "Transhumanism ve AI.", activity: "Transhumanizm nedir? Felsefik bir deneme yaz." },
    { week: 22, title: "AI ve Sanatin Gelecegi", description: "Sanatci-AI isbirligi.", activity: "AI ile bir sanat eseri uret. Sanatsal surecinni belgele." },
    { week: 23, title: "Hesaplamali Yaraticilik", description: "AI yaraticilik olcumu.", activity: "Bir AI nin yaraticilığini nasil olcersin? Metrik oneri yap." },
    { week: 24, title: "Global AI Yonetisimi", description: "BM, uluslararasi isbirligi.", activity: "Global bir AI yonetisim cercevesi oner." },
    { week: 25, title: "AI ve Bilim", description: "Yapay bilincin imkani.", activity: "Integrated Information Theory yi arastir." },
    { week: 26, title: "Uzun Vadeli AI Guvenligi", description: "MIRI, Anthropic arastirrmalari.", activity: "AI alignment in en zor 3 problemini arastir." },
    { week: 27, title: "Arastirma Portfoyu", description: "Akademik kimligini olustur.", activity: "Google Scholar profilini olustur. Ilk makalenin taslagini yap." },
    { week: 28, title: "Kapsamli Final Projesi", description: "Ozgun arastirma.", activity: "Ozgun bir AI arastirmasi tasarla." },
    { week: 29, title: "Proje: Arastirma Yurutme", description: "Deneyi uygula.", activity: "Arastirmani yurut. Gunluk ilerleme notu tut." },
    { week: 30, title: "Proje: Analiz", description: "Sonuclari derinlemesine analiz et.", activity: "Sonucllarini istatistiksel ve teorik olarak analiz et." },
    { week: 31, title: "Proje: Makale Yazimi", description: "Conference/journal formati.", activity: "Arastirmani NeurIPS formatinda yaz." },
    { week: 32, title: "Proje: Sunum Hazirligi", description: "Akademik konferans sunumu.", activity: "25 dakikalik akademik sunum + poster hazirla." },
    { week: 33, title: "Akran Degerlendirmesi Ileri", description: "Cift kor degerlendirme.", activity: "Iki makaleyi cift kor peer review yap." },
    { week: 34, title: "Proje Finalizasyonu", description: "Yayina hazir hale getir.", activity: "Makaleni bir arxiv preprint olarak yayinla." },
    { week: 35, title: "Final Konferansi", description: "Akademik sunum.", activity: "Arastirmani sun." },
    { week: 36, title: "Mezuniyet ve Gelecek", description: "AI kariyerine hazirlanma.", activity: "Hedef universite ve arastirma grubuna basvuru planin. Mektup taslagi yaz." },
  ],
}
`;

fs.writeFileSync('src/data/curriculum.js', content);
console.log('curriculum.js created successfully!');
